// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhImgM1LKQa-OPnpDMmmTIb0p_nt3zhFg',
    appId: '1:222466984920:web:d3a46086f8cfddcc02c0ad',
    messagingSenderId: '222466984920',
    projectId: 'library-azer123654',
    authDomain: 'library-azer123654.firebaseapp.com',
    storageBucket: 'library-azer123654.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvX32FNaMzTamtfZ6O7gX5JmTzjBiQfQ',
    appId: '1:222466984920:android:503e53fc90365aef02c0ad',
    messagingSenderId: '222466984920',
    projectId: 'library-azer123654',
    storageBucket: 'library-azer123654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNp3Inu_gjylYi4muezeAj_S6jLdC1_eo',
    appId: '1:222466984920:ios:0db9d34434eb8faa02c0ad',
    messagingSenderId: '222466984920',
    projectId: 'library-azer123654',
    storageBucket: 'library-azer123654.appspot.com',
    iosClientId: '222466984920-4j6vlui96aonre9mpvq85hf1631l5177.apps.googleusercontent.com',
    iosBundleId: 'library',
  );
}
